version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.13
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: myflaskapp
      MYSQL_USER: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_ROOT_PASSWORD: hudsondata
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro